// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CardsController from "./cards_controller"
application.register("cards", CardsController)

import ChooseDepartmentsController from "./choose_departments_controller"
application.register("choose-departments", ChooseDepartmentsController)

import CustomToastMessageController from "./custom_toast_message_controller"
application.register("custom-toast-message", CustomToastMessageController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MessageController from "./message_controller"
application.register("message", MessageController)

import SlimSelectController from "./slim_select_controller"
application.register("slim-select", SlimSelectController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import ToDoAddNestedFormController from "./to_do_add_nested_form_controller"
application.register("to-do-add-nested-form", ToDoAddNestedFormController)

import ToDoListEditController from "./to_do_list_edit_controller"
application.register("to-do-list-edit", ToDoListEditController)

import ToDoListUpdateStatusController from "./to_do_list_update_status_controller"
application.register("to-do-list-update-status", ToDoListUpdateStatusController)

import TurboModalController from "./turbo_modal_controller"
application.register("turbo-modal", TurboModalController)
