# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/annoucements', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Annoucement. As you add validations to Annoucement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Annoucement.create! valid_attributes
      get annoucements_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      annoucement = Annoucement.create! valid_attributes
      get annoucement_url(annoucement)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_annoucement_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      annoucement = Annoucement.create! valid_attributes
      get edit_annoucement_url(annoucement)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Annoucement' do
        expect do
          post annoucements_url, params: { annoucement: valid_attributes }
        end.to change(Annoucement, :count).by(1)
      end

      it 'redirects to the created annoucement' do
        post annoucements_url, params: { annoucement: valid_attributes }
        expect(response).to redirect_to(annoucement_url(Annoucement.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Annoucement' do
        expect do
          post annoucements_url, params: { annoucement: invalid_attributes }
        end.to change(Annoucement, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post annoucements_url, params: { annoucement: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested annoucement' do
        annoucement = Annoucement.create! valid_attributes
        patch annoucement_url(annoucement), params: { annoucement: new_attributes }
        annoucement.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the annoucement' do
        annoucement = Annoucement.create! valid_attributes
        patch annoucement_url(annoucement), params: { annoucement: new_attributes }
        annoucement.reload
        expect(response).to redirect_to(annoucement_url(annoucement))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        annoucement = Annoucement.create! valid_attributes
        patch annoucement_url(annoucement), params: { annoucement: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested annoucement' do
      annoucement = Annoucement.create! valid_attributes
      expect do
        delete annoucement_url(annoucement)
      end.to change(Annoucement, :count).by(-1)
    end

    it 'redirects to the annoucements list' do
      annoucement = Annoucement.create! valid_attributes
      delete annoucement_url(annoucement)
      expect(response).to redirect_to(annoucements_url)
    end
  end
end
